---

version: '3'
services:

  pinger:
    build:
      dockerfile: docker/Dockerfile
      context: ../
    environment:
      APP_ENV: production
      LOG_LEVEL: debug
      DB: postgres://pingmonitor:pingmonitor@postgres/pingmonitor
      PING_INTERVAL: 5
      PING_TIMEOUT: 67
    links:
      - postgres
    restart: on-failure
    command: /bin/bash -c "bundle exec bin/pinger 1>&2"

  web:
    build:
      dockerfile: docker/Dockerfile
      context: ../
    environment:
      APP_ENV: production
      DB: postgres://pingmonitor:pingmonitor@postgres/pingmonitor
    links:
      - postgres
    ports:
      - 9292:9292
    expose:
      - 9292
    restart: on-failure
    command: /bin/bash -c "bundle exec rackup --host 0.0.0.0 --server thin 1>&2"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: pingmonitor
      POSTGRES_USER: pingmonitor
      POSTGRES_DB: pingmonitor
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    restart: on-failure

volumes:
  postgres_data:
